"""added new tables

Revision ID: 719d8c9d5954
Revises: 921f5659aa74
Create Date: 2023-09-20 14:00:41.692938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719d8c9d5954'
down_revision = '921f5659aa74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_chat_history_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_user_chat_history_id_user_chat_history'), 'user_chat_history', ['user_chat_history_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_user_chat_history_id_user_chat_history'), type_='foreignkey')
        batch_op.drop_column('user_chat_history_id')

    # ### end Alembic commands ###
